# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('credid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits', models.IntegerField(default=0)),
                ('details', models.CharField(max_length=180)),
                ('used', models.BooleanField(default=True)),
                ('companycredid', models.CharField(default='----', max_length=200)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.companies')),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=30)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('credits', models.IntegerField(default=0)),
                ('ld', models.DateField()),
                ('phno', models.IntegerField(max_length=10)),
                ('blood_type', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'AB+'), ('6', 'AB-'), ('7', 'O+'), ('8', 'O-')], default='1', max_length=5)),
                ('otp', models.IntegerField(default=0)),
                ('otpdate', models.DateTimeField(null=True)),
                ('verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.donor'),
        ),
    ]
