# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='lat',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='ld',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
